### ISSUE TITLE
No module named 'call_function_with_timeout'

### ISSUE THREAD

**Issue by AnshVM** [AJ730/xss#3]
**Describe the bug**
`No module named 'call_function_with_timeout'`
When I try to run 
`python3 xsstrike.py -u  "https://0ac300d30448104e835c0f1a003200b3.web-security-academy.net/"`

**Screenshots**
![image](https://github.com/AJ730/XSStrikeMod/assets/70061826/a2647ff7-9fd5-48b6-a17c-e15d80664a30)

**Potential cause or fix**
None

**Environment:**
 - OS: WSL Ubuntu 22.04
 - Python version: 3.10.6

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Comment by AJ730** [comment]
It seems we have not added this in the requirements. Can you pip install call_function_with_timout?

**Comment by catsmells** [comment]
> It seems we have not added this in the requirements. Can you pip install call_function_with_timout?

No module found.
